version: '2'

services:

 redis:
  container_name: redis
  image: redis
  restart: always

 cdn:
  container_name: cdn
  image: rester/rester-cdn
  restart: always
  volumes:
  - ./api.files:/var/www/html/files
  #- ../rester-cdn/src/rester:/var/www/html/rester
  ports:
  - '8888:80'

 db:
  container_name: db
  image: mariadb
  restart: always
  ports:
  - 3306:3306
  volumes:
  - ./data.sql:/docker-entrypoint-initdb.d/dump.sql
  #-- ./database:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: "park!981qq"
   MYSQL_DATABASE: "designtopf_naver.com"
   MYSQL_USER: "designtopf_naver.com"
   MYSQL_PASSWORD: "designtopf"

 sql:
  container_name: sql
  image: rester/rester-sql
  restart: always
  links:
  - redis:cache.rester.kr
  - db:db.rester.kr
  volumes:
  - ./sql:/var/www/html/modules
  - ./sql.cfg:/var/www/cfg:ro
  - ../rester-sql/src/rester:/var/www/html/rester

 api:
  container_name: api
  image: rester/rester-php
  restart: always
  links:
  - sql:sql.rester.kr
  volumes:
  - ./api:/var/www/html/modules
  - ./api.cfg:/var/www/cfg:ro
  - ./api.files:/var/www/html/rester/files
    # - ../rester-php/src/rester:/var/www/html/rester
    # - ../rester-php/src/index.php:/var/www/html/index.php
  ports:
  - '8082:80'
            
 adm:
  container_name: adm
  image: rester/rester-frontend
  restart: always
  links:
  - api:api.rester.kr
  volumes:
  - ./adm:/var/www/html
  - ./adm.cfg:/var/www/cfg
  - ../rester-frontend/lib:/var/www/lib
  ports:
  - '8083:80'

 frontend:
  container_name: frontend
  image: rester/rester-frontend
  restart: always
  links:
  - api:api.rester.kr
  volumes:
  - ./front:/var/www/html
  - ./front.cfg:/var/www/cfg
  - ../rester-frontend/default.conf:/etc/nginx/sites-available/default.conf:ro
  - ../rester-frontend/lib:/var/www/lib
  ports:
  - '80:80'
