version: '2'

services:

# cache redis server
 redis:
  container_name: redis
  image: redis
  restart: always
  ports:
  - 6379:6379

# sample database
 db:
  container_name: db
  image: mariadb
  restart: always
  ports:
    - 3306:3306
  volumes:
    - ./example_db.sql:/docker-entrypoint-initdb.d/dump.sql
  environment:
   MYSQL_RANDOM_ROOT_PASSWORD: "yes"
   MYSQL_DATABASE: "example"
   MYSQL_USER: "rester"
   MYSQL_PASSWORD: "rester"

 sql:
  container_name: sql
  image: kevinpark/rester-sql
  restart: always
  links:
  - redis:cache.rester.kr
  - db:db.rester.kr
  volumes:
  - //Github/rester-sql/src/rester:/var/www/html/rester
  - ./sql:/var/www/html/modules
  - ./sql.cfg:/var/www/cfg:ro
  ports:
  - '8081:80'

 rester-php:
  container_name: rester-php
  image: kevinpark/nginx-php-redis
  restart: always
  links:
    - redis:cache.rester.kr
    - sql:sql.rester.kr
  volumes:
   - ./default.conf:/etc/nginx/sites-available/default.conf:ro
   - ./src:/var/www/html
   - ./cfg:/var/www/cfg:ro
  ports:
  - '80:80'
